version: '3.9' # Use a modern version

services:
  stockdata_app: # Renamed service for clarity
    build: . # Build the image from the Dockerfile in the current directory
    container_name: tem-price # Optional: Give the container a specific name
    ports:
      - "8082:8082" # Map host port 8082 to container port 8082
    volumes:
      # Persist the SQLite DB and query_counts.json on the host
      - ${DATA_DIR}:/app/instance
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - shared-net

networks:
  shared-net:
    external: true
